/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.recognitionApp.userEnterApp;

import com.mycompany.recognitionApp.Capture.RegisterPerson;
import com.mycompany.recognitionApp.Recognize.Recognizer;
import com.mycompany.recognitionApp.connectToDB.Conn;
import com.mycompany.recognitionApp.connectToDB.ModelOfCriminal;
import com.mycompany.recognitionApp.cardButtons.Card;
import com.mycompany.recognitionApp.dbOfCriminals.displayCriminals;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu(String username) {
        initComponents();
        welcomeUser.setText("Welcome,  " + username + "!");

        setCaptureCard();
        setRecognizeCard();
        setDataCard();
    }

    public void setCaptureCard(){
        captureCard.setColors(new Color(204,204,255), new Color(204,204,255));
        captureCard.setTitle("Capture");

        Conn connection = new Conn();
        Integer lastId = null;
        connection.connect();
        connection.executeSQL("SELECT * FROM criminal ORDER BY id DESC LIMIT 1");
        try {
            connection.rs.first();
            String name = connection.rs.getString("first_name") + " " + connection.rs.getString("last_name");
            lastId = connection.rs.getInt("id");
            captureCard.setDescription("Last captured: " + name);
        } catch (SQLException e) {
            captureCard.setDescription("No one was captured");
        }

        dataCard.setDescription("Number of people: " + lastId);
        captureCard.setIcon(new ImageIcon("D:\\icons8-capture-30.png"));
    }

    public void setRecognizeCard(){
        recognizeCard.setColors(new Color(153,153,255), new Color(153,153,255));
        recognizeCard.setTitle("Recognize");
        recognizeCard.setDescription("Recognize a person");
        recognizeCard.setIcon(new ImageIcon("D:\\icons8-face-recognized-function-in-high-end-smartphone-with-depth-sensor-28.png"));
    }

    public void setDataCard(){
        dataCard.setColors(new Color(153,102,255), new Color(153,102,255));
        dataCard.setTitle("Data");
        dataCard.setIcon(new ImageIcon("D:\\icons8-data-encryption-30.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1 = new Card();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        welcomeUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        recognizeCard = new Card();
        captureCard = new Card();
        dataCard = new Card();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jLabel3.setText("Welcome to face recognizer PELIGRO!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\people_security (1).jpg"));

        welcomeUser.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        welcomeUser.setForeground(new java.awt.Color(102, 102, 255));
        welcomeUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeUser.setText("Welcome, user!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setText("PELIGRO - your face recognizer");

        recognizeCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recognizeCardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recognizeCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recognizeCardMouseExited(evt);
            }
        });

        captureCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                captureCardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                captureCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                captureCardMouseExited(evt);
            }
        });

        dataCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataCardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataCardMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("What do you want to do? Choose an option");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(128, 128, 128)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recognizeCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(captureCard, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(welcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(131, 131, 131))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(welcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(captureCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(recognizeCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(dataCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void captureCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_captureCardMouseEntered
        // TODO add your handling code here:
        captureCard.setColors(new Color(153,231,255, 255), new Color(153,231,255, 255));
    }//GEN-LAST:event_captureCardMouseEntered

    private void captureCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_captureCardMouseExited
        // TODO add your handling code here:
        captureCard.setColors(new Color(204,204,255), new Color(204,204,255));
    }//GEN-LAST:event_captureCardMouseExited

    private void recognizeCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recognizeCardMouseEntered
        // TODO add your handling code here:
        recognizeCard.setColors(new Color(100,205,255, 255), new Color(100,205,255, 255));
    }//GEN-LAST:event_recognizeCardMouseEntered

    private void recognizeCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recognizeCardMouseExited
        // TODO add your handling code here:
        recognizeCard.setColors(new Color(153,153,255), new Color(153,153,255));
    }//GEN-LAST:event_recognizeCardMouseExited

    private void dataCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataCardMouseEntered
        // TODO add your handling code here:
        dataCard.setColors(new Color(82,191,255, 255), new Color(82,191,255, 255));
    }//GEN-LAST:event_dataCardMouseEntered

    private void dataCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataCardMouseExited
        // TODO add your handling code here:
        dataCard.setColors(new Color(153,102,255), new Color(153,102,255));
    }//GEN-LAST:event_dataCardMouseExited

    private void captureCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_captureCardMouseClicked
        // TODO add your handling code here:
        RegisterPerson registerPerson = new RegisterPerson();
        registerPerson.setVisible(true);
        registerPerson.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        registerPerson.setLocationRelativeTo(null);
        //dispose();
           
    }//GEN-LAST:event_captureCardMouseClicked

    private void recognizeCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recognizeCardMouseClicked
        // TODO add your handling code here:
        Recognizer recognizer = new Recognizer();
        recognizer.setVisible(true);
        recognizer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        recognizer.setLocationRelativeTo(null);
    }//GEN-LAST:event_recognizeCardMouseClicked


    private void dataCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataCardMouseClicked

        Conn connection = new Conn();
        connection.connect();
        connection.executeSQL("SELECT * FROM criminal");
        ArrayList<ModelOfCriminal> criminals = new ArrayList<>();
        try{
            ResultSet rs = connection.rs;//rs.getInt("id"),
            while (rs.next()){
                ModelOfCriminal criminal = new ModelOfCriminal(rs.getString("first_name"),
                        rs.getString("last_name"), rs.getString("dob"), rs.getString("age"),
                        rs.getString("gender"), rs.getString("phone_number"), rs.getString("city"),
                        rs.getString("state"));
                criminals.add(criminal);
            }
        } catch (SQLException e){

        }


        displayCriminals dbCriminals = new displayCriminals(criminals);
        dbCriminals.setVisible(true);
        dbCriminals.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dbCriminals.setLocationRelativeTo(null);
        connection.disconnect();
    }//GEN-LAST:event_dataCardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu("Kate").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Card captureCard;
    private Card card1;
    private Card dataCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private Card recognizeCard;
    private javax.swing.JLabel welcomeUser;
    // End of variables declaration//GEN-END:variables
}
